accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from accounts.views import login_form


urlpatterns = [

    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", login_form, name="signup"),

]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(pattern_name="home")),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView,
    ReceiptCreate,
    ExpenseCategoryListView,
    AccountsView,
    ExpenseCategoryCreateView,
    AccountCreateView
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreate.as_view(), name="create_receipt"),
    path("categories/", ExpenseCategoryListView.as_view(), name="list_categories"), # noqa
    path("accounts/", AccountsView.as_view(), name="list_account"),
    path("categories/create/", ExpenseCategoryCreateView.as_view(), name="create_category"),  # noqa
    path("accounts/create/", AccountCreateView.as_view(), name="create_account"), # noqa
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.contrib.auth.models import User


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(User, related_name="categories", on_delete=models.CASCADE)  # noqa

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(User, related_name="accounts", on_delete=models.CASCADE) # noqa

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField(null=True)
    purchaser = models.ForeignKey(User, related_name="receipts", on_delete=models.CASCADE) # noqa
    category = models.ForeignKey("ExpenseCategory", related_name="receipts", on_delete=models.CASCADE) # noqa
    account = models.ForeignKey("Account", related_name="receipts", on_delete=models.CASCADE, null=True) # noqa

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def login_form(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'registration/signup.html', context)

receipts/views.py
from receipts.models import Receipt, ExpenseCategory, Account
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.shortcuts import redirect


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = 'receipts/list.html'

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreate(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = 'receipts/create_receipt.html'
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect('home')


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = 'receipts/expenses.html'

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountsView(LoginRequiredMixin, ListView):
    model = Account
    template_name = 'receipts/accounts_list.html'

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = 'receipts/create_category.html'
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect('list_categories')


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = 'receipts/create_account.html'
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect('list_account')

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                            <a href="{% url 'list_categories' %}">Categories</a>
                            <a href="{% url 'create_category' %}">Create New Category</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'signup' %}">Signup</a>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% block pagination %}
            {% endblock pagination %}
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

receipts/templates/receipts/accounts_list.html
{% extends "../base.html" %}

<title>Accounts List</title>
{% block content %}
    <main>
        <h1>Reg Accounts</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>Number of Receipts</th>
                </tr>
            </thead>
            {% for accounts in account_list %}
                <tbody>
                    <tr>
                        <td>{{ accounts.name }}</td>
                        <td>{{ accounts.number }}</td>
                        <td>{{ accounts.receipts.all }}</td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
    </main>
{% endblock content %}

receipts/templates/receipts/create_account.html
{% extends "base.html" %}
{% block content %}
<main>
    <div>
        <h1>Create Account</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
</main>
{% endblock content %}

receipts/templates/receipts/create_category.html
{% extends "base.html" %}

{% block content %}
    <main>
        <div>
            <h1>Create Category</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/create_receipt.html
{% extends "../base.html" %}

<title>CreateReceipt</title>
{% block content %}
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipts/expenses.html
{% extends "../base.html" %}

<title>Document</title>
{% block content %}
    <main>
        <h1>My Expenses</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of Receipts</th>
                </tr>
            </thead>
            {% for category in expensecategory_list %}
                <tbody>
                    <tr>
                        <td>{{ category.name }}</td>
                        <td>{{ category.receipts.all|length }}</td>
                    </tr>
                </tbody>
            {% endfor %}
        </table>
    </main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends "../base.html" %}

<title>Receipts</title>
{% block content %}
<main>
    <h1>My Receipts</h1>
    <table>
        <thead>
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </tr>
        </thead>
        {% for receipt in receipt_list %}
            <tbody>
                <tr>
                    <td>{{ receipt.vendor }}</td>
                    <td>{{ receipt.total }}</td>
                    <td>{{ receipt.tax }}</td>
                    <td>{{ receipt.date|date:"m-d-Y" }}</td>
                    <td>{{ receipt.category }}</td>
                    <td>{{ receipt.account }}</td>
                </tr>
            </tbody>
        {% endfor %}
    </table>
</main>
{% endblock content %}